name: nodf
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - dipy=1.6.0
  - pip=23.0.1
  - python=3.8.16
  - pytorch=2.0.0
  - pytorch-lightning=2.1.0
  - tensorboard=2.14.1
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - nibabel=5.0.1
  - pip:
      - image-similarity-measures==0.3.6