name: nodf
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=2.0.0
  - aiosignal=1.3.1
  - blas=1.0
  - blinker=1.6.3
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cachetools=5.3.1
  - certifi=2023.11.17
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.12.1
  - cytoolz=0.12.0
  - dask-core=2023.4.1
  - ffmpeg=4.3
  - filelock=3.9.0
  - flit-core=3.8.0
  - freetype=2.12.1
  - fsspec=2023.9.2
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.23.3
  - google-auth-oauthlib=1.0.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - icu=67.1
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.31.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcurl=7.88.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.5
  - markupsafe=2.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - numexpr=2.8.4
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - partd=1.4.1
  - pillow=9.4.0
  - pip=23.0.1
  - pooch=1.7.0
  - protobuf=3.20.3
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=23.0.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - seaborn=0.12.2
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.1
  - sympy=1.11.1
  - tensorboard=2.14.1
  - tensorboard-data-server=0.7.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - werkzeug=3.0.0
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohttp==3.8.6
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-timeout==4.0.3
      - attrs==22.2.0
      - ax-platform==0.3.3
      - backcall==0.2.0
      - beautifulsoup4==4.12.0
      - bleach==6.0.0
      - botorch==0.8.5
      - comm==0.1.3
      - debugpy==1.6.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dipy==1.6.0
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - gpytorch==1.10
      - h5py==3.8.0
      - icosphere==0.1.3
      - image-similarity-measures==0.3.6
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - ipykernel==6.22.0
      - ipython==8.11.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.4
      - isoduration==20.11.0
      - jedi==0.18.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.1.0
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==1.1.3
      - lazy-loader==0.4
      - lightning==2.1.0
      - lightning-utilities==0.9.0
      - linear-operator==0.4.0
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - multidict==6.0.4
      - multipledispatch==0.6.0
      - nbclassic==0.5.3
      - nbclient==0.7.2
      - nbconvert==7.2.10
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - nibabel==5.0.1
      - notebook==6.5.3
      - notebook-shim==0.2.2
      - numpy==1.24.4
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - packaging==23.0
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - phasepack==1.5
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.1.1
      - plotly==5.13.1
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.14.0
      - pygsp==0.5.1
      - pyro-api==0.1.2
      - pyro-ppl==1.8.4
      - pyrsistent==0.19.3
      - python-json-logger==2.0.7
      - pytorch-lightning==2.1.0
      - pytz==2023.2
      - pyyaml==6.0
      - pyzmq==25.0.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - send2trash==1.8.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - stack-data==0.6.2
      - tenacity==8.2.2
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - torchmetrics==1.2.0
      - tornado==6.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typeguard==2.13.3
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - widgetsnbextension==3.6.3
      - yarl==1.9.2
      - zipp==3.15.0
